export const countries = [
  { label: '🇦🇫 Afghanistan', value: 'af' },
  { label: '🇦🇱 Albania', value: 'al' },
  { label: '🇩🇿 Algeria', value: 'dz' },
  { label: '🇦🇴 Angola', value: 'ao' },
  { label: '🇦🇷 Argentina', value: 'ar' },
  { label: '🇦🇲 Armenia', value: 'am' },
  { label: '🇦🇺 Australia', value: 'au' },
  { label: '🇦🇹 Austria', value: 'at' },
  { label: '🇦🇿 Azerbaijan', value: 'az' },
  { label: '🇧🇩 Bangladesh', value: 'bd' },
  { label: '🇧🇾 Belarus', value: 'by' },
  { label: '🇧🇪 Belgium', value: 'be' },
  { label: '🇧🇯 Benin', value: 'bj' },
  { label: '🇧🇴 Bolivia', value: 'bo' },
  { label: '🇧🇦 Bosnia and Herzegovina', value: 'ba' },
  { label: '🇧🇷 Brazil', value: 'br' },
  { label: '🇧🇬 Bulgaria', value: 'bg' },
  { label: '🇧🇫 Burkina Faso', value: 'bf' },
  { label: '🇧🇮 Burundi', value: 'bi' },
  { label: '🇰🇭 Cambodia', value: 'kh' },
  { label: '🇨🇲 Cameroon', value: 'cm' },
  { label: '🇨🇦 Canada', value: 'ca' },
  { label: '🇨🇫 Central African Republic', value: 'cf' },
  { label: '🇨🇱 Chile', value: 'cl' },
  { label: '🇨🇳 China', value: 'cn' },
  { label: '🇨🇴 Colombia', value: 'co' },
  { label: '🇨🇩 Congo (DRC)', value: 'cd' },
  { label: '🇨🇬 Congo (Republic)', value: 'cg' },
  { label: '🇨🇷 Costa Rica', value: 'cr' },
  { label: '🇭🇷 Croatia', value: 'hr' },
  { label: '🇨🇺 Cuba', value: 'cu' },
  { label: '🇨🇾 Cyprus', value: 'cy' },
  { label: '🇨🇿 Czechia', value: 'cz' },
  { label: '🇩🇰 Denmark', value: 'dk' },
  { label: '🇩🇴 Dominican Republic', value: 'do' },
  { label: '🇪🇨 Ecuador', value: 'ec' },
  { label: '🇪🇬 Egypt', value: 'eg' },
  { label: '🇸🇻 El Salvador', value: 'sv' },
  { label: '🇪🇪 Estonia', value: 'ee' },
  { label: '🇪🇹 Ethiopia', value: 'et' },
  { label: '🇫🇮 Finland', value: 'fi' },
  { label: '🇫🇷 France', value: 'fr' },
  { label: '🇬🇪 Georgia', value: 'ge' },
  { label: '🇩🇪 Germany', value: 'de' },
  { label: '🇬🇭 Ghana', value: 'gh' },
  { label: '🇬🇷 Greece', value: 'gr' },
  { label: '🇬🇹 Guatemala', value: 'gt' },
  { label: '🇬🇳 Guinea', value: 'gn' },
  { label: '🇭🇹 Haiti', value: 'ht' },
  { label: '🇭🇳 Honduras', value: 'hn' },
  { label: '🇭🇺 Hungary', value: 'hu' },
  { label: '🇮🇸 Iceland', value: 'is' },
  { label: '🇮🇳 India', value: 'in' },
  { label: '🇮🇩 Indonesia', value: 'id' },
  { label: '🇮🇷 Iran', value: 'ir' },
  { label: '🇮🇶 Iraq', value: 'iq' },
  { label: '🇮🇪 Ireland', value: 'ie' },
  { label: '🇮🇱 Israel', value: 'il' },
  { label: '🇮🇹 Italy', value: 'it' },
  { label: '🇯🇲 Jamaica', value: 'jm' },
  { label: '🇯🇵 Japan', value: 'jp' },
  { label: '🇯🇴 Jordan', value: 'jo' },
  { label: '🇰🇿 Kazakhstan', value: 'kz' },
  { label: '🇰🇪 Kenya', value: 'ke' },
  { label: '🇽🇰 Kosovo', value: 'xk' },
  { label: '🇰🇼 Kuwait', value: 'kw' },
  { label: '🇰🇬 Kyrgyzstan', value: 'kg' },
  { label: '🇱🇦 Laos', value: 'la' },
  { label: '🇱🇻 Latvia', value: 'lv' },
  { label: '🇱🇧 Lebanon', value: 'lb' },
  { label: '🇱🇾 Libya', value: 'ly' },
  { label: '🇱🇹 Lithuania', value: 'lt' },
  { label: '🇱🇺 Luxembourg', value: 'lu' },
  { label: '🇲🇰 North Macedonia', value: 'mk' },
  { label: '🇲🇬 Madagascar', value: 'mg' },
  { label: '🇲🇼 Malawi', value: 'mw' },
  { label: '🇲🇾 Malaysia', value: 'my' },
  { label: '🇲🇱 Mali', value: 'ml' },
  { label: '🇲🇷 Mauritania', value: 'mr' },
  { label: '🇲🇽 Mexico', value: 'mx' },
  { label: '🇲🇩 Moldova', value: 'md' },
  { label: '🇲🇳 Mongolia', value: 'mn' },
  { label: '🇲🇦 Morocco', value: 'ma' },
  { label: '🇲🇿 Mozambique', value: 'mz' },
  { label: '🇲🇲 Myanmar', value: 'mm' },
  { label: '🇳🇦 Namibia', value: 'na' },
  { label: '🇳🇵 Nepal', value: 'np' },
  { label: '🇳🇱 Netherlands', value: 'nl' },
  { label: '🇳🇿 New Zealand', value: 'nz' },
  { label: '🇳🇮 Nicaragua', value: 'ni' },
  { label: '🇳🇪 Niger', value: 'ne' },
  { label: '🇳🇬 Nigeria', value: 'ng' },
  { label: '🇰🇵 North Korea', value: 'kp' },
  { label: '🇳🇴 Norway', value: 'no' },
  { label: '🇴🇲 Oman', value: 'om' },
  { label: '🇵🇰 Pakistan', value: 'pk' },
  { label: '🇵🇦 Panama', value: 'pa' },
  { label: '🇵🇬 Papua New Guinea', value: 'pg' },
  { label: '🇵🇾 Paraguay', value: 'py' },
  { label: '🇵🇪 Peru', value: 'pe' },
  { label: '🇵🇭 Philippines', value: 'ph' },
  { label: '🇵🇱 Poland', value: 'pl' },
  { label: '🇵🇹 Portugal', value: 'pt' },
  { label: '🇵🇷 Puerto Rico', value: 'pr' },
  { label: '🇶🇦 Qatar', value: 'qa' },
  { label: '🇷🇴 Romania', value: 'ro' },
  { label: '🇷🇺 Russia', value: 'ru' },
  { label: '🇷🇼 Rwanda', value: 'rw' },
  { label: '🇸🇦 Saudi Arabia', value: 'sa' },
  { label: '🇸🇳 Senegal', value: 'sn' },
  { label: '🇷🇸 Serbia', value: 'rs' },
  { label: '🇸🇱 Sierra Leone', value: 'sl' },
  { label: '🇸🇬 Singapore', value: 'sg' },
  { label: '🇸🇰 Slovakia', value: 'sk' },
  { label: '🇸🇮 Slovenia', value: 'si' },
  { label: '🇿🇦 South Africa', value: 'za' },
  { label: '🇰🇷 South Korea', value: 'kr' },
  { label: '🇪🇸 Spain', value: 'es' },
  { label: '🇱🇰 Sri Lanka', value: 'lk' },
  { label: '🇸🇩 Sudan', value: 'sd' },
  { label: '🇸🇪 Sweden', value: 'se' },
  { label: '🇨🇭 Switzerland', value: 'ch' },
  { label: '🇸🇾 Syria', value: 'sy' },
  { label: '🇹🇼 Taiwan', value: 'tw' },
  { label: '🇹🇯 Tajikistan', value: 'tj' },
  { label: '🇹🇿 Tanzania', value: 'tz' },
  { label: '🇹🇭 Thailand', value: 'th' },
  { label: '🇹🇬 Togo', value: 'tg' },
  { label: '🇹🇹 Trinidad and Tobago', value: 'tt' },
  { label: '🇹🇳 Tunisia', value: 'tn' },
  { label: '🇹🇷 Turkey', value: 'tr' },
  { label: '🇺🇬 Uganda', value: 'ug' },
  { label: '🇺🇦 Ukraine', value: 'ua' },
  { label: '🇦🇪 United Arab Emirates', value: 'ae' },
  { label: '🇬🇧 United Kingdom', value: 'gb' },
  { label: '🇺🇸 United States', value: 'us' },
  { label: '🇺🇾 Uruguay', value: 'uy' },
  { label: '🇺🇿 Uzbekistan', value: 'uz' },
  { label: '🇻🇪 Venezuela', value: 've' },
  { label: '🇻🇳 Vietnam', value: 'vn' },
  { label: '🇾🇪 Yemen', value: 'ye' },
  { label: '🇿🇲 Zambia', value: 'zm' },
  { label: '🇿🇼 Zimbabwe', value: 'zw' },
];